services:
  shopping-list:
    build: shopping-list
    image: shopping-list
    restart: "no"
    volumes:
      - ./shopping-list/:/app
    ports:
      - 7777:7777
    depends_on:
      - database
      - flyway
    env_file:
      - project.env

  database:
    container_name: laurenzooz-shopping-list-db
    image: postgres:latest
    restart: "no"
    env_file:
        - project.env

  flyway:
    image: flyway/flyway:latest-alpine
    depends_on:
      - database
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env
