steps:
  # need checkout before using docker-compose-action
  - uses: actions/checkout@v3
  - uses: adambirds/docker-compose-action@v1.3.0
    with:
      up-flags: "--entrypoint=npx"
      down-flags: "--volumes"
      test-container: laurenzooz-shopping-list-db
      test-command: "e2e-playwright playwright test"
