name: Run e2e tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Build and run Docker Compose
      run: |
        docker-compose up -d

    - name: Debugging
      run: |
        docker ps -a
        docker network ls
        docker network inspect shopping-list_default
        netstat -lt
        curl -v http://127.0.0.1:7777

    - name: Run e2e tests
      run: docker-compose run --entrypoint=npx e2e-playwright playwright test

    - name: Shutdown Docker Compose
      run: docker-compose down
