name: Playwright e2e

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  playwright:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Wait for application to be ready
      run: |
        for i in {1..30}; do
          if curl -s http://localhost:7777 > /dev/null; then
            break
          else
            echo "Waiting for application to be ready..."
            sleep 10
          fi
        done

    - name: Run test
      run: docker-compose run --entrypoint=npx e2e-playwright playwright test
