name: Playwright e2e

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  playwright:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: vx.x.x # Latest
        
    - name: Install Playwright
      run: npx playwright install --with-deps

    - name: Run test
      run: docker-compose run --entrypoint=npx e2e-playwright playwright test

    - name: Clean
      run: docker-compose rm -sf

